-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE blog_post_inventory_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  blog_post_id INTEGER NOT NULL,
  inventory_id INTEGER NOT NULL,
  keyword_matched TEXT NOT NULL,
  link_position INTEGER,
  created_at INTEGER NOT NULL DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)),
  FOREIGN KEY (blog_post_id) REFERENCES blog_posts(id) ON DELETE CASCADE,
  FOREIGN KEY (inventory_id) REFERENCES master_inventory(id) ON DELETE CASCADE,
  UNIQUE(blog_post_id, inventory_id)
);

CREATE TABLE blog_posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  body TEXT DEFAULT '',
  cover_image TEXT,
  author TEXT DEFAULT 'Frame & Reel',
  status TEXT DEFAULT 'draft',
  published_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
, tags TEXT DEFAULT '', featured INTEGER DEFAULT 0, theme TEXT DEFAULT '');

CREATE TABLE catalog (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title_english TEXT NOT NULL,
  title_local TEXT,
  director TEXT,
  year INTEGER,
  synopsis TEXT,
  tmdb_id TEXT,
  genre TEXT,
  main_cast TEXT,
  created_at INTEGER NOT NULL DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)),
  updated_at INTEGER NOT NULL DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)),
  UNIQUE(title_english, director, year)
);

CREATE TABLE contact_messages (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL, message TEXT NOT NULL, name TEXT, created_at INTEGER);

CREATE TABLE distributor_registry (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, country TEXT, is_modern_reissue INTEGER DEFAULT 0, logo_patterns TEXT, known_codes TEXT, created_at INTEGER DEFAULT (strftime('%s', 'now') * 1000));

CREATE TABLE ebay_auth (id INTEGER PRIMARY KEY CHECK (id = 1), access_token TEXT, refresh_token TEXT, expires_at INTEGER, seller_username TEXT);

CREATE TABLE ebay_listings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  inventory_id INTEGER REFERENCES inventory(id),
  ebay_item_id TEXT UNIQUE,
  ebay_status TEXT DEFAULT 'active',
  parsed_english_title TEXT,
  parsed_original_title TEXT,
  parsed_year INTEGER,
  parsed_release_year INTEGER,
  parsed_director TEXT,
  parsed_actors TEXT,
  parsed_format TEXT,
  parsed_artist TEXT,
  parsed_condition TEXT,
  parsed_country TEXT,
  raw_description TEXT,
  created_at INTEGER,
  ended_at INTEGER,
  updated_at INTEGER
);

CREATE TABLE entity_tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tag_id INTEGER NOT NULL,
  entity_type TEXT NOT NULL CHECK(entity_type IN ('inventory', 'blog', 'image')),
  entity_id INTEGER NOT NULL,
  approved INTEGER NOT NULL DEFAULT 0,
  suggested_by TEXT DEFAULT 'manual',
  created_at INTEGER NOT NULL DEFAULT (cast(unixepoch('subsecond') * 1000 as integer))
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE image_library (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename TEXT NOT NULL,
  content_type TEXT DEFAULT 'image/jpeg',
  s3_uri TEXT NOT NULL,
  thumbnail_url TEXT,
  ocr_text TEXT,
  identified_title TEXT,
  identified_year INTEGER,
  identified_director TEXT,
  identified_genre TEXT,
  identified_actors TEXT,
  identified_data TEXT,
  matched_inventory_id INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
, lot_number TEXT DEFAULT NULL, item_number TEXT DEFAULT NULL, upload_note TEXT DEFAULT NULL, poster_format TEXT DEFAULT NULL, release_type TEXT DEFAULT NULL, dimensions TEXT DEFAULT NULL, year_range_start integer DEFAULT NULL, year_range_end integer DEFAULT NULL, source_url TEXT, condition TEXT, printer_credit TEXT, distributor TEXT, original_release_year INTEGER, re_release_year INTEGER, title_original TEXT, title_local TEXT, artist_name TEXT, style_variant TEXT, nss_visa_code TEXT, is_verified INTEGER DEFAULT 0, detected_condition TEXT, condition_summary TEXT, audit_status TEXT DEFAULT 'pending', truth_strip_s3_uri TEXT, tags TEXT DEFAULT '', ai_reasoning TEXT, internal_notes TEXT, print_year INTEGER, tmdb_id INTEGER, conflict_status TEXT DEFAULT 'none', conflict_reason TEXT, poster_country TEXT DEFAULT NULL, lot_id VARCHAR(255), billing_block TEXT DEFAULT '', artist_credit TEXT DEFAULT '', edition_variant TEXT DEFAULT '', estimated_print_year TEXT DEFAULT '', release_type_evidence TEXT DEFAULT '', match_confidence REAL, match_status TEXT DEFAULT 'unmatched', suggested_inventory_id INTEGER, matched_title TEXT, matched_year INTEGER, matched_format TEXT, matched_lot_id TEXT, matched_item_number TEXT);

CREATE TABLE inventory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT,
  original_title TEXT,
  year INTEGER,
  director TEXT,
  actors TEXT,
  genre TEXT,
  format TEXT,
  dimensions TEXT,
  ds_ss TEXT DEFAULT 'SS',
  artist TEXT,
  movie_country TEXT,
  poster_country TEXT,
  poster_style TEXT,
  awards TEXT,
  item_type TEXT DEFAULT 'individual',
  lot_id TEXT,
  item_number TEXT NOT NULL UNIQUE,
  sold INTEGER DEFAULT 0,
  price REAL,
  condition_grade TEXT,
  source_url TEXT,
  visibility TEXT DEFAULT 'listed',
  notes TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER DEFAULT NULL,
  ebay_item_id TEXT DEFAULT NULL,
  ebay_price REAL DEFAULT NULL,
  ebay_status TEXT DEFAULT NULL,
  pricing_markup REAL DEFAULT 0,
  source TEXT DEFAULT 'manual',
  ebay_bundle_url TEXT,
  image_source TEXT DEFAULT NULL,
  tags TEXT DEFAULT '',
  collectors_note TEXT DEFAULT '',
  ebay_description TEXT DEFAULT '',
  condition_notes TEXT DEFAULT '',
  shipping_info TEXT DEFAULT '',
  international_shipping TEXT DEFAULT '',
  combined_shipping TEXT DEFAULT '',
  format_description TEXT DEFAULT NULL
, release_year INTEGER, release_type TEXT DEFAULT 'original', printer_credit TEXT, nss_code TEXT, distributor_logo TEXT, billing_block_style TEXT, audit_status TEXT DEFAULT 'pending');

CREATE TABLE inventory_bundle_items (id INTEGER PRIMARY KEY AUTOINCREMENT, bundle_id INTEGER NOT NULL, child_inventory_id INTEGER NOT NULL, quantity INTEGER DEFAULT 1);

CREATE TABLE linked_listings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  unit_id INTEGER NOT NULL REFERENCES units(id) ON DELETE CASCADE,
  platform_name TEXT NOT NULL DEFAULT 'ebay',
  platform_item_id TEXT,
  price REAL,
  listing_status TEXT DEFAULT 'draft',
  listing_url TEXT,
  created_at INTEGER NOT NULL DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)),
  updated_at INTEGER NOT NULL DEFAULT (cast(unixepoch('subsecond') * 1000 as integer))
);

CREATE TABLE master_credits_ledger (id INTEGER PRIMARY KEY AUTOINCREMENT, entity_type TEXT NOT NULL, name TEXT NOT NULL, verified_name TEXT, tmdb_id TEXT, imdb_id TEXT, country TEXT, poster_count INTEGER DEFAULT 0, last_verified_at INTEGER, created_at INTEGER DEFAULT (strftime('%s', 'now') * 1000), updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000), UNIQUE(entity_type, name));

CREATE TABLE master_inventory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lot_id VARCHAR(255) NOT NULL UNIQUE,
  title_original VARCHAR(255),
  title_local VARCHAR(255),
  ocr_title_raw TEXT,
  movie_release_year INTEGER,
  poster_year INTEGER,
  poster_country VARCHAR(100),
  printer_credit TEXT,
  nss_visa_code VARCHAR(100),
  ebay_listing_ids TEXT,
  dna_audit_status VARCHAR(50) DEFAULT 'pending',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ebay_order_id TEXT UNIQUE,
  legacy_order_id TEXT,
  buyer_username TEXT,
  buyer_email TEXT,
  total_amount REAL,
  total_currency TEXT DEFAULT 'USD',
  status TEXT DEFAULT 'PENDING',
  payment_status TEXT DEFAULT '',
  created_at INTEGER,
  paid_at INTEGER,
  shipped_at INTEGER,
  shipping_address TEXT,
  line_items TEXT DEFAULT '[]',
  synced_at INTEGER,
  notes TEXT DEFAULT ''
);

CREATE TABLE poster_images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  upload_id INTEGER NOT NULL REFERENCES poster_uploads(id),
  s3_uri TEXT NOT NULL,
  split_index INTEGER DEFAULT 0,
  created_at INTEGER NOT NULL
);

CREATE TABLE poster_uploads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  original_filename TEXT NOT NULL,
  original_s3_uri TEXT NOT NULL,
  status TEXT DEFAULT 'uploaded',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE posters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  image_id INTEGER NOT NULL UNIQUE,
  title TEXT,
  year INTEGER,
  director TEXT,
  actors TEXT,
  genre TEXT,
  plot TEXT,
  poster_style TEXT,
  awards TEXT,
  tmdb_id TEXT,
  status TEXT DEFAULT 'pending',
  price REAL,
  condition TEXT,
  notes TEXT,
  scanned_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  visibility TEXT DEFAULT 'hidden',
  title_original TEXT,
  title_local TEXT,
  artist_name TEXT,
  printer_credit TEXT,
  style_variant TEXT,
  nss_visa_code TEXT,
  release_type TEXT DEFAULT 'original',
  is_verified INTEGER DEFAULT 0,
  detected_condition TEXT,
  condition_summary TEXT,
  audit_status TEXT DEFAULT 'pending'
, is_just_in INTEGER DEFAULT 0);

CREATE TABLE provenance_audits (id INTEGER PRIMARY KEY AUTOINCREMENT, poster_id INTEGER NOT NULL, tier1_title TEXT, tier1_confidence REAL, tier2_director_id TEXT, tier2_actor_ids TEXT, tier2_year INTEGER, tier2_confidence REAL, tier3_distributor TEXT, tier3_printer_credit TEXT, tier3_tax_codes TEXT, tier3_confidence REAL, overall_confidence REAL DEFAULT 0, edition_status TEXT DEFAULT 'unknown', provenance_conflict INTEGER DEFAULT 0, audit_notes TEXT, created_at INTEGER DEFAULT (strftime('%s', 'now') * 1000), updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000), FOREIGN KEY(poster_id) REFERENCES posters(id));

CREATE TABLE sheet_config (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  sheet_id TEXT NOT NULL,
  tab_name TEXT NOT NULL DEFAULT 'Sheet1',
  last_sync_at INTEGER,
  sync_status TEXT DEFAULT 'disconnected',
  created_at INTEGER NOT NULL DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)),
  updated_at INTEGER NOT NULL DEFAULT (cast(unixepoch('subsecond') * 1000 as integer))
, service_account_email TEXT DEFAULT 'frame-reel-sync@frame-and-reel.iam.gserviceaccount.com');

CREATE TABLE subscribers (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE, created_at INTEGER);

CREATE TABLE tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'general',
  created_at INTEGER DEFAULT (cast(unixepoch('subsecond') * 1000 as integer))
);

CREATE TABLE units (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  catalog_id INTEGER NOT NULL REFERENCES catalog(id) ON DELETE CASCADE,
  serial_id TEXT NOT NULL,
  format TEXT,
  condition_grade TEXT,
  cost_basis REAL,
  storage_location TEXT,
  notes TEXT,
  created_at INTEGER NOT NULL DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)),
  updated_at INTEGER NOT NULL DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)), ai_reasoning TEXT, internal_notes TEXT,
  UNIQUE(serial_id)
);

-- INDEXS

CREATE INDEX contact_messages_created_idx ON contact_messages(created_at);

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX idx_blog_posts_published ON blog_posts(published_at DESC);

CREATE INDEX idx_blog_posts_slug ON blog_posts(slug);

CREATE INDEX idx_blog_posts_status ON blog_posts(status);

CREATE INDEX idx_bundle_items_child ON inventory_bundle_items(child_inventory_id);

CREATE INDEX idx_catalog_director ON catalog(director);

CREATE INDEX idx_catalog_title_english ON catalog(title_english);

CREATE INDEX idx_catalog_tmdb ON catalog(tmdb_id);

CREATE INDEX idx_entity_tags_approved ON entity_tags(approved);

CREATE INDEX idx_entity_tags_entity ON entity_tags(entity_type, entity_id);

CREATE INDEX idx_entity_tags_tag ON entity_tags(tag_id);

CREATE INDEX idx_image_library_created ON image_library(created_at DESC);

CREATE INDEX idx_image_library_matched ON image_library(matched_inventory_id);

CREATE INDEX idx_listings_ebay ON linked_listings(platform_item_id) WHERE platform_name = 'ebay';

CREATE INDEX idx_listings_platform ON linked_listings(platform_name);

CREATE INDEX idx_listings_status ON linked_listings(listing_status);

CREATE INDEX idx_listings_unit ON linked_listings(unit_id);

CREATE INDEX idx_master_inventory_lot_id ON master_inventory(lot_id);

CREATE INDEX idx_tags_name ON tags(name);

CREATE INDEX idx_tags_type ON tags(type);

CREATE INDEX idx_units_catalog ON units(catalog_id);

CREATE INDEX idx_units_condition ON units(condition_grade);

CREATE INDEX idx_units_serial ON units(serial_id);

CREATE INDEX orders_created_idx ON orders(created_at DESC);

CREATE INDEX orders_status_idx ON orders(status);

CREATE INDEX poster_images_upload_idx ON poster_images(upload_id);

CREATE INDEX poster_uploads_status_idx ON poster_uploads(status);

CREATE INDEX poster_uploads_user_idx ON poster_uploads(user_id);

CREATE INDEX subscribers_email_idx ON subscribers(email);
