// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { relations } from "drizzle-orm/relations";
import { posterUploads, posterImages, posters, provenanceAudits, catalog, units, linkedListings, masterInventory, blogPostInventoryLinks, blogPosts, inventory, ebayListings } from "./db_schema";

export const posterImagesRelations = relations(posterImages, ({one}) => ({
	posterUpload: one(posterUploads, {
		fields: [posterImages.uploadId],
		references: [posterUploads.id]
	}),
}));

export const posterUploadsRelations = relations(posterUploads, ({many}) => ({
	posterImages: many(posterImages),
}));

export const provenanceAuditsRelations = relations(provenanceAudits, ({one}) => ({
	poster: one(posters, {
		fields: [provenanceAudits.posterId],
		references: [posters.id]
	}),
}));

export const postersRelations = relations(posters, ({many}) => ({
	provenanceAudits: many(provenanceAudits),
}));

export const unitsRelations = relations(units, ({one, many}) => ({
	catalog: one(catalog, {
		fields: [units.catalogId],
		references: [catalog.id]
	}),
	linkedListings: many(linkedListings),
}));

export const catalogRelations = relations(catalog, ({many}) => ({
	units: many(units),
}));

export const linkedListingsRelations = relations(linkedListings, ({one}) => ({
	unit: one(units, {
		fields: [linkedListings.unitId],
		references: [units.id]
	}),
}));

export const blogPostInventoryLinksRelations = relations(blogPostInventoryLinks, ({one}) => ({
	masterInventory: one(masterInventory, {
		fields: [blogPostInventoryLinks.inventoryId],
		references: [masterInventory.id]
	}),
	blogPost: one(blogPosts, {
		fields: [blogPostInventoryLinks.blogPostId],
		references: [blogPosts.id]
	}),
}));

export const masterInventoryRelations = relations(masterInventory, ({many}) => ({
	blogPostInventoryLinks: many(blogPostInventoryLinks),
}));

export const blogPostsRelations = relations(blogPosts, ({many}) => ({
	blogPostInventoryLinks: many(blogPostInventoryLinks),
}));

export const ebayListingsRelations = relations(ebayListings, ({one}) => ({
	inventory: one(inventory, {
		fields: [ebayListings.inventoryId],
		references: [inventory.id]
	}),
}));

export const inventoryRelations = relations(inventory, ({many}) => ({
	ebayListings: many(ebayListings),
}));